// Template definitions for the Landing Page Builder
// Each template is a CraftJS-serialized page state

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  targetAudience: string;
  psychologyTactics: string[];
  tags: string[];
  accentColor: string;
  gradientFrom: string;
  gradientTo: string;
  emoji: string;
  json: string;
}

// ─── Template 1: Agency Growth Machine ───────────────────────────────────────
const agencyGrowthTemplate: TemplateDefinition = {
  id: 'agency-growth',
  name: 'Agency Growth Machine',
  description: 'High-authority B2B funnel built to convert cold agency leads into retainer clients. Uses ROI framing, authority signals, and risk reversal.',
  targetAudience: 'Marketing Agencies · B2B SaaS · Consultants',
  psychologyTactics: ['Authority', 'ROI Framing', 'Social Proof', 'Risk Reversal', 'Scarcity'],
  tags: ['B2B', 'SaaS', 'Agency'],
  accentColor: '#6366f1',
  gradientFrom: '#0F0B2A',
  gradientTo: '#020412',
  emoji: '🚀',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['ag_hero', 'ag_proof', 'ag_features', 'ag_testimonials', 'ag_pricing', 'ag_faq', 'ag_cta'],
      linkedNodes: {},
    },
    ag_hero: {
      type: { resolvedName: 'HeroSection' },
      isCanvas: false,
      props: { layout: 'centered', backgroundColor: '#02040A', paddingTop: 100, paddingBottom: 100 },
      displayName: 'Hero Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_proof: {
      type: { resolvedName: 'SocialProofSection' },
      isCanvas: false,
      props: { backgroundColor: '#070A13', paddingTop: 50, paddingBottom: 50, accentColor: '#6366f1', sectionLabel: 'TRUSTED BY 500+ AGENCIES WORLDWIDE' },
      displayName: 'Social Proof Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_features: {
      type: { resolvedName: 'FeaturesSection' },
      isCanvas: false,
      props: { layout: 'cards', backgroundColor: '#02040A', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Features Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_testimonials: {
      type: { resolvedName: 'TestimonialsSection' },
      isCanvas: false,
      props: { backgroundColor: '#030712', paddingTop: 80, paddingBottom: 80, accentColor: '#FBBF24', sectionLabel: 'AGENCY OWNERS LOVE US', sectionTitle: "Results Speak Louder Than Promises" },
      displayName: 'Testimonials Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_pricing: {
      type: { resolvedName: 'PricingSection' },
      isCanvas: false,
      props: { backgroundColor: '#02040A', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Pricing Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_faq: {
      type: { resolvedName: 'FAQSection' },
      isCanvas: false,
      props: { backgroundColor: '#070A13', paddingTop: 80, paddingBottom: 80 },
      displayName: 'FAQ Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    ag_cta: {
      type: { resolvedName: 'CTASection' },
      isCanvas: false,
      props: { backgroundColor: '#0F0B2A', accentColor: '#6366f1', paddingTop: 100, paddingBottom: 100, urgencyText: '⚡ FOUNDING MEMBER PRICING — LIMITED SPOTS', showUrgency: true, gradientOverlay: true },
      displayName: 'CTA Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
  }),
};

// ─── Template 2: Flash Sale Crusher ──────────────────────────────────────────
const flashSaleTemplate: TemplateDefinition = {
  id: 'flash-sale',
  name: 'Flash Sale Crusher',
  description: 'High-urgency e-commerce funnel engineered for impulse buyers. Countdown timer, scarcity framing, and bold price anchoring drive maximum conversions.',
  targetAudience: 'E-Commerce · Flash Sales · Product Launches',
  psychologyTactics: ['FOMO', 'Urgency', 'Scarcity', 'Price Anchoring', 'Impulse Buying'],
  tags: ['E-Commerce', 'Urgency', 'Product'],
  accentColor: '#EF4444',
  gradientFrom: '#1A0505',
  gradientTo: '#020202',
  emoji: '🔥',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['fs_hero', 'fs_timer', 'fs_proof', 'fs_features', 'fs_testimonials', 'fs_pricing', 'fs_cta'],
      linkedNodes: {},
    },
    fs_hero: {
      type: { resolvedName: 'HeroSection' },
      isCanvas: false,
      props: { layout: 'image-right', backgroundColor: '#0A0202', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Hero Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_timer: {
      type: { resolvedName: 'CountdownTimer' },
      isCanvas: false,
      props: { title: '🔥 FLASH SALE ENDS IN — PRICE GOES UP AFTER', backgroundColor: '#0D0101', accentColor: '#EF4444', textColor: '#ffffff', showDays: false, padding: 32 },
      displayName: 'Countdown Timer',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_proof: {
      type: { resolvedName: 'SocialProofBar' },
      isCanvas: false,
      props: { count: '47,000', unit: 'orders shipped', rating: '4.8', reviewCount: '12,400', badge: 'Bestseller', backgroundColor: '#080101', accentColor: '#F59E0B', padding: 20 },
      displayName: 'Social Proof Bar',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_features: {
      type: { resolvedName: 'FeaturesSection' },
      isCanvas: false,
      props: { layout: 'grid-3', backgroundColor: '#040101', paddingTop: 70, paddingBottom: 70 },
      displayName: 'Features Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_testimonials: {
      type: { resolvedName: 'TestimonialsSection' },
      isCanvas: false,
      props: { backgroundColor: '#080101', paddingTop: 70, paddingBottom: 70, accentColor: '#F59E0B', sectionLabel: 'WHAT CUSTOMERS ARE SAYING', sectionTitle: 'Why 47,000+ Customers Keep Coming Back' },
      displayName: 'Testimonials Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_pricing: {
      type: { resolvedName: 'PricingSection' },
      isCanvas: false,
      props: { backgroundColor: '#040101', paddingTop: 70, paddingBottom: 70 },
      displayName: 'Pricing Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    fs_cta: {
      type: { resolvedName: 'CTASection' },
      isCanvas: false,
      props: { backgroundColor: '#100505', accentColor: '#EF4444', paddingTop: 80, paddingBottom: 80, urgencyText: '🔥 SALE ENDS AT MIDNIGHT — PRICE DOUBLES TOMORROW', showUrgency: true, gradientOverlay: true },
      displayName: 'CTA Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
  }),
};

// ─── Template 3: Life Transformation Blueprint ────────────────────────────────
const transformationTemplate: TemplateDefinition = {
  id: 'transformation',
  name: 'Life Transformation Blueprint',
  description: 'Emotion-driven coaching funnel using the Pain → Dream → Fix framework. Deep empathy, transformation stories, and aspirational outcomes lead to high enrollment rates.',
  targetAudience: 'Online Courses · Life Coaching · Masterminds',
  psychologyTactics: ['Pain-Dream-Fix', 'Empathy', 'Aspiration', 'Transformation Story', 'Authority'],
  tags: ['Coaching', 'Course', 'Membership'],
  accentColor: '#10b981',
  gradientFrom: '#051A10',
  gradientTo: '#020A05',
  emoji: '✨',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['tr_hero', 'tr_proof', 'tr_features', 'tr_testimonials', 'tr_pricing', 'tr_faq', 'tr_leadgen'],
      linkedNodes: {},
    },
    tr_hero: {
      type: { resolvedName: 'HeroSection' },
      isCanvas: false,
      props: { layout: 'centered', backgroundColor: '#020D06', paddingTop: 100, paddingBottom: 100 },
      displayName: 'Hero Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_proof: {
      type: { resolvedName: 'SocialProofSection' },
      isCanvas: false,
      props: { backgroundColor: '#030F07', paddingTop: 50, paddingBottom: 50, accentColor: '#10b981', sectionLabel: 'TRUSTED BY 8,000+ STUDENTS IN 47 COUNTRIES' },
      displayName: 'Social Proof Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_features: {
      type: { resolvedName: 'FeaturesSection' },
      isCanvas: false,
      props: { layout: 'zigzag', backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Features Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_testimonials: {
      type: { resolvedName: 'TestimonialsSection' },
      isCanvas: false,
      props: { backgroundColor: '#030F07', paddingTop: 80, paddingBottom: 80, accentColor: '#FBBF24', sectionLabel: 'LIVES TRANSFORMED', sectionTitle: 'Real Students. Real Breakthroughs.' },
      displayName: 'Testimonials Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_pricing: {
      type: { resolvedName: 'PricingSection' },
      isCanvas: false,
      props: { backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Pricing Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_faq: {
      type: { resolvedName: 'FAQSection' },
      isCanvas: false,
      props: { backgroundColor: '#030F07', paddingTop: 80, paddingBottom: 80 },
      displayName: 'FAQ Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    tr_leadgen: {
      type: { resolvedName: 'LeadGenSection' },
      isCanvas: false,
      props: { backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 },
      displayName: 'Lead Gen Section',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
  }),
};

// ─── Auxiliary Pages for Agency Growth Machine ───────────────────────────────
const agencyGrowthCheckout: TemplateDefinition = {
  id: 'agency-growth-checkout',
  name: 'Agency Growth - Checkout (Page 2)',
  description: 'High-converting checkout page for the Agency Growth funnel.',
  targetAudience: 'Marketing Agencies · B2B SaaS · Consultants',
  psychologyTactics: ['Urgency', 'Risk Reversal', 'Social Proof'],
  tags: ['B2B', 'Checkout', 'Agency'],
  accentColor: '#6366f1',
  gradientFrom: '#0F0B2A',
  gradientTo: '#020412',
  emoji: '🛒',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['agc_pricing', 'agc_proof', 'agc_faq'],
      linkedNodes: {},
    },
    agc_pricing: { type: { resolvedName: 'PricingSection' }, isCanvas: false, props: { backgroundColor: '#02040A', paddingTop: 80, paddingBottom: 80 }, displayName: 'Pricing Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    agc_proof: { type: { resolvedName: 'SocialProofSection' }, isCanvas: false, props: { backgroundColor: '#070A13', paddingTop: 50, paddingBottom: 50, accentColor: '#6366f1' }, displayName: 'Social Proof Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    agc_faq: { type: { resolvedName: 'FAQSection' }, isCanvas: false, props: { backgroundColor: '#02040A', paddingTop: 80, paddingBottom: 80 }, displayName: 'FAQ Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const agencyGrowthUpsell: TemplateDefinition = {
  id: 'agency-growth-upsell',
  name: 'Agency Growth - Upsell/Downsell (Page 3)',
  description: 'One-time offer upsell page to increase AOV.',
  targetAudience: 'Marketing Agencies · B2B SaaS · Consultants',
  psychologyTactics: ['FOMO', 'Scarcity', 'Impulse Buying'],
  tags: ['B2B', 'Upsell', 'Agency'],
  accentColor: '#6366f1',
  gradientFrom: '#0F0B2A',
  gradientTo: '#020412',
  emoji: '📈',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['agu_cta', 'agu_features'],
      linkedNodes: {},
    },
    agu_cta: { type: { resolvedName: 'CTASection' }, isCanvas: false, props: { backgroundColor: '#0F0B2A', accentColor: '#6366f1', paddingTop: 100, paddingBottom: 100, urgencyText: 'WAIT! SPECIAL ONE-TIME OFFER', showUrgency: true, gradientOverlay: true }, displayName: 'CTA Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    agu_features: { type: { resolvedName: 'FeaturesSection' }, isCanvas: false, props: { layout: 'cards', backgroundColor: '#02040A', paddingTop: 80, paddingBottom: 80 }, displayName: 'Features Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const agencyGrowthThankYou: TemplateDefinition = {
  id: 'agency-growth-thankyou',
  name: 'Agency Growth - Thank You (Page 4)',
  description: 'Order confirmation and next steps for the Agency Growth funnel.',
  targetAudience: 'Marketing Agencies · B2B SaaS · Consultants',
  psychologyTactics: ['Authority', 'Aspiration'],
  tags: ['B2B', 'Thank You', 'Agency'],
  accentColor: '#6366f1',
  gradientFrom: '#0F0B2A',
  gradientTo: '#020412',
  emoji: '🎉',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['agt_hero'],
      linkedNodes: {},
    },
    agt_hero: { type: { resolvedName: 'HeroSection' }, isCanvas: false, props: { layout: 'centered', backgroundColor: '#02040A', paddingTop: 150, paddingBottom: 150 }, displayName: 'Hero Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

// ─── Auxiliary Pages for Flash Sale Crusher ──────────────────────────────────
const flashSaleCheckout: TemplateDefinition = {
  id: 'flash-sale-checkout',
  name: 'Flash Sale - Checkout (Page 2)',
  description: 'High-urgency checkout page to finalize impulse purchases.',
  targetAudience: 'E-Commerce · Flash Sales · Product Launches',
  psychologyTactics: ['Urgency', 'Scarcity', 'Social Proof'],
  tags: ['E-Commerce', 'Checkout', 'Urgency'],
  accentColor: '#EF4444',
  gradientFrom: '#1A0505',
  gradientTo: '#020202',
  emoji: '🛒',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['fsc_timer', 'fsc_pricing', 'fsc_proof'],
      linkedNodes: {},
    },
    fsc_timer: { type: { resolvedName: 'CountdownTimer' }, isCanvas: false, props: { title: '🔥 FLASH SALE ENDS IN — PRICE GOES UP AFTER', backgroundColor: '#0D0101', accentColor: '#EF4444', textColor: '#ffffff', showDays: false, padding: 32 }, displayName: 'Countdown Timer', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    fsc_pricing: { type: { resolvedName: 'PricingSection' }, isCanvas: false, props: { backgroundColor: '#040101', paddingTop: 70, paddingBottom: 70 }, displayName: 'Pricing Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    fsc_proof: { type: { resolvedName: 'SocialProofBar' }, isCanvas: false, props: { count: '47,000', unit: 'orders shipped', rating: '4.8', reviewCount: '12,400', badge: 'Bestseller', backgroundColor: '#080101', accentColor: '#F59E0B', padding: 20 }, displayName: 'Social Proof Bar', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const flashSaleUpsell: TemplateDefinition = {
  id: 'flash-sale-upsell',
  name: 'Flash Sale - Upsell/Downsell (Page 3)',
  description: 'Limited-time bundle offer to increase AOV on impulse purchases.',
  targetAudience: 'E-Commerce · Flash Sales · Product Launches',
  psychologyTactics: ['FOMO', 'Price Anchoring', 'Impulse Buying'],
  tags: ['E-Commerce', 'Upsell', 'Urgency'],
  accentColor: '#EF4444',
  gradientFrom: '#1A0505',
  gradientTo: '#020202',
  emoji: '📦',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['fsu_cta', 'fsu_testimonials'],
      linkedNodes: {},
    },
    fsu_cta: { type: { resolvedName: 'CTASection' }, isCanvas: false, props: { backgroundColor: '#100505', accentColor: '#EF4444', paddingTop: 80, paddingBottom: 80, urgencyText: '🔥 WAIT! ADD THIS TO YOUR ORDER FOR 50% OFF', showUrgency: true, gradientOverlay: true }, displayName: 'CTA Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    fsu_testimonials: { type: { resolvedName: 'TestimonialsSection' }, isCanvas: false, props: { backgroundColor: '#080101', paddingTop: 70, paddingBottom: 70, accentColor: '#F59E0B', sectionLabel: 'WHAT CUSTOMERS ARE SAYING', sectionTitle: 'Why 47,000+ Customers Keep Coming Back' }, displayName: 'Testimonials Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const flashSaleThankYou: TemplateDefinition = {
  id: 'flash-sale-thankyou',
  name: 'Flash Sale - Thank You (Page 4)',
  description: 'Order confirmation page.',
  targetAudience: 'E-Commerce · Flash Sales · Product Launches',
  psychologyTactics: ['Social Proof', 'Authority'],
  tags: ['E-Commerce', 'Thank You', 'Urgency'],
  accentColor: '#EF4444',
  gradientFrom: '#1A0505',
  gradientTo: '#020202',
  emoji: '🎉',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['fst_hero'],
      linkedNodes: {},
    },
    fst_hero: { type: { resolvedName: 'HeroSection' }, isCanvas: false, props: { layout: 'centered', backgroundColor: '#0A0202', paddingTop: 150, paddingBottom: 150 }, displayName: 'Hero Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

// ─── Auxiliary Pages for Life Transformation Blueprint ─────────────────────────
const transformationCheckout: TemplateDefinition = {
  id: 'transformation-checkout',
  name: 'Life Transformation - Checkout (Page 2)',
  description: 'Checkout page engineered for courses and coaching programs.',
  targetAudience: 'Online Courses · Life Coaching · Masterminds',
  psychologyTactics: ['Risk Reversal', 'Empathy', 'Social Proof'],
  tags: ['Coaching', 'Checkout', 'Course'],
  accentColor: '#10b981',
  gradientFrom: '#051A10',
  gradientTo: '#020A05',
  emoji: '🛒',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['trc_pricing', 'trc_testimonials', 'trc_faq'],
      linkedNodes: {},
    },
    trc_pricing: { type: { resolvedName: 'PricingSection' }, isCanvas: false, props: { backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 }, displayName: 'Pricing Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    trc_testimonials: { type: { resolvedName: 'TestimonialsSection' }, isCanvas: false, props: { backgroundColor: '#030F07', paddingTop: 80, paddingBottom: 80, accentColor: '#FBBF24', sectionLabel: 'LIVES TRANSFORMED', sectionTitle: 'Real Students. Real Breakthroughs.' }, displayName: 'Testimonials Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    trc_faq: { type: { resolvedName: 'FAQSection' }, isCanvas: false, props: { backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 }, displayName: 'FAQ Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const transformationUpsell: TemplateDefinition = {
  id: 'transformation-upsell',
  name: 'Life Transformation - Upsell/Downsell (Page 3)',
  description: 'Upsell for 1-on-1 coaching or inner circle mastermind access.',
  targetAudience: 'Online Courses · Life Coaching · Masterminds',
  psychologyTactics: ['Aspiration', 'FOMO', 'Authority'],
  tags: ['Coaching', 'Upsell', 'Course'],
  accentColor: '#10b981',
  gradientFrom: '#051A10',
  gradientTo: '#020A05',
  emoji: '🚀',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['tru_cta', 'tru_features'],
      linkedNodes: {},
    },
    tru_cta: { type: { resolvedName: 'CTASection' }, isCanvas: false, props: { backgroundColor: '#030F07', accentColor: '#10b981', paddingTop: 100, paddingBottom: 100, urgencyText: 'WAIT! WANT 1-ON-1 GUIDANCE?', showUrgency: true, gradientOverlay: true }, displayName: 'CTA Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    tru_features: { type: { resolvedName: 'FeaturesSection' }, isCanvas: false, props: { layout: 'zigzag', backgroundColor: '#020D06', paddingTop: 80, paddingBottom: 80 }, displayName: 'Features Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const transformationThankYou: TemplateDefinition = {
  id: 'transformation-thankyou',
  name: 'Life Transformation - Thank You (Page 4)',
  description: 'Welcome page and onboarding steps.',
  targetAudience: 'Online Courses · Life Coaching · Masterminds',
  psychologyTactics: ['Empathy', 'Aspiration', 'Community'],
  tags: ['Coaching', 'Thank You', 'Course'],
  accentColor: '#10b981',
  gradientFrom: '#051A10',
  gradientTo: '#020A05',
  emoji: '🎊',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['trt_hero', 'trt_leadgen'],
      linkedNodes: {},
    },
    trt_hero: { type: { resolvedName: 'HeroSection' }, isCanvas: false, props: { layout: 'centered', backgroundColor: '#020D06', paddingTop: 100, paddingBottom: 100 }, displayName: 'Hero Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    trt_leadgen: { type: { resolvedName: 'LeadGenSection' }, isCanvas: false, props: { backgroundColor: '#030F07', paddingTop: 80, paddingBottom: 80 }, displayName: 'Lead Gen Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

// ─── Restaurant Templates (E-Commerce) ───────────────────────────────────────
const restaurantDark: TemplateDefinition = {
  id: 'restaurant-v2-dark',
  name: 'Restaurant v2 Dark',
  description: 'Dark mode e-commerce template for restaurants and food delivery, inspired by popular delivery apps.',
  targetAudience: 'Restaurants · Food Delivery · E-Commerce',
  psychologyTactics: ['Appetite Appeal', 'Urgency', 'Social Proof', 'Impulse Buying'],
  tags: ['E-Commerce', 'Restaurant', 'Dark'],
  accentColor: '#EF4444',
  gradientFrom: '#1c1c1c',
  gradientTo: '#000000',
  emoji: '🍔',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['rd_hero', 'rd_features', 'rd_testimonials', 'rd_pricing', 'rd_cta'],
      linkedNodes: {},
    },
    rd_hero: { type: { resolvedName: 'HeroSection' }, isCanvas: false, props: { layout: 'centered', backgroundColor: '#0A0A0A', paddingTop: 80, paddingBottom: 80 }, displayName: 'Hero Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rd_features: { type: { resolvedName: 'FeaturesSection' }, isCanvas: false, props: { layout: 'cards', backgroundColor: '#111111', paddingTop: 70, paddingBottom: 70 }, displayName: 'Menu Categories', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rd_testimonials: { type: { resolvedName: 'TestimonialsSection' }, isCanvas: false, props: { backgroundColor: '#0A0A0A', paddingTop: 70, paddingBottom: 70, accentColor: '#EF4444', sectionLabel: 'REVIEWS', sectionTitle: 'What Foodies Are Saying' }, displayName: 'Reviews Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rd_pricing: { type: { resolvedName: 'PricingSection' }, isCanvas: false, props: { backgroundColor: '#111111', paddingTop: 70, paddingBottom: 70 }, displayName: 'Featured Items Pricing', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rd_cta: { type: { resolvedName: 'CTASection' }, isCanvas: false, props: { backgroundColor: '#050505', accentColor: '#EF4444', paddingTop: 80, paddingBottom: 80, urgencyText: 'WEEKEND SPECIAL - ORDER NOW FOR FAST DELIVERY', showUrgency: true, gradientOverlay: true }, displayName: 'CTA Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

const restaurantLight: TemplateDefinition = {
  id: 'restaurant-v2-light',
  name: 'Restaurant v2 Light',
  description: 'Light mode e-commerce template for restaurants and food delivery, featuring a clean and bright aesthetic.',
  targetAudience: 'Restaurants · Food Delivery · E-Commerce',
  psychologyTactics: ['Appetite Appeal', 'Urgency', 'Social Proof', 'Impulse Buying'],
  tags: ['E-Commerce', 'Restaurant', 'Light'],
  accentColor: '#EF4444',
  gradientFrom: '#f9fafb',
  gradientTo: '#ffffff',
  emoji: '🍽️',
  json: JSON.stringify({
    ROOT: {
      type: { resolvedName: 'Container' },
      isCanvas: true,
      props: {},
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['rl_hero', 'rl_features', 'rl_testimonials', 'rl_pricing', 'rl_cta'],
      linkedNodes: {},
    },
    rl_hero: { type: { resolvedName: 'HeroSection' }, isCanvas: false, props: { layout: 'centered', backgroundColor: '#ffffff', paddingTop: 80, paddingBottom: 80 }, displayName: 'Hero Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rl_features: { type: { resolvedName: 'FeaturesSection' }, isCanvas: false, props: { layout: 'cards', backgroundColor: '#f9fafb', paddingTop: 70, paddingBottom: 70 }, displayName: 'Menu Categories', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rl_testimonials: { type: { resolvedName: 'TestimonialsSection' }, isCanvas: false, props: { backgroundColor: '#ffffff', paddingTop: 70, paddingBottom: 70, accentColor: '#EF4444', sectionLabel: 'REVIEWS', sectionTitle: 'What Foodies Are Saying' }, displayName: 'Reviews Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rl_pricing: { type: { resolvedName: 'PricingSection' }, isCanvas: false, props: { backgroundColor: '#f9fafb', paddingTop: 70, paddingBottom: 70 }, displayName: 'Featured Items Pricing', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
    rl_cta: { type: { resolvedName: 'CTASection' }, isCanvas: false, props: { backgroundColor: '#ffffff', accentColor: '#EF4444', paddingTop: 80, paddingBottom: 80, urgencyText: 'WEEKEND SPECIAL - ORDER NOW FOR FAST DELIVERY', showUrgency: true, gradientOverlay: true }, displayName: 'CTA Section', custom: {}, hidden: false, nodes: [], linkedNodes: {}, parent: 'ROOT' },
  }),
};

export const LANDING_PAGE_TEMPLATES: TemplateDefinition[] = [
  agencyGrowthTemplate,
  agencyGrowthCheckout,
  agencyGrowthUpsell,
  agencyGrowthThankYou,
  flashSaleTemplate,
  flashSaleCheckout,
  flashSaleUpsell,
  flashSaleThankYou,
  transformationTemplate,
  transformationCheckout,
  transformationUpsell,
  transformationThankYou,
  restaurantDark,
  restaurantLight,
];
