"use client";

import { useState } from "react";
import Link from "next/link";
import { 
  Sparkles, 
  Workflow, 
  Database, 
  ShieldCheck, 
  ArrowRight, 
  Coins, 
  Check, 
  Plus, 
  Minus,
  Code,
  Store,
  Stethoscope,
  Briefcase,
  GraduationCap,
  MessageSquare,
  Quote,
  Star
} from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

export default function MarketingLandingPage() {
  const [activeFAQ, setActiveFAQ] = useState<number | null>(null);
  const [selectedCurrency, setSelectedCurrency] = useState<"USD" | "INR">("USD");

  const [chatInput, setChatInput] = useState("");
  const [chatMessages, setChatMessages] = useState<Array<{ role: "user" | "assistant"; content: string }>>([
    { role: "assistant", content: "Hi! I am the Aether AI Agent. Ask me about our vector indexing, dual-region Stripe/Razorpay billing, or custom n8n webhooks!" }
  ]);
  const [isTyping, setIsTyping] = useState(false);

  const handleFAQToggle = (index: number) => {
    setActiveFAQ(activeFAQ === index ? null : index);
  };

  const handleDemoChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || isTyping) return;

    const userText = chatInput;
    setChatMessages(prev => [...prev, { role: "user", content: userText }]);
    setChatInput("");
    setIsTyping(true);

    // Simulated high-fidelity response in 1 second
    setTimeout(() => {
      let botResponse = "Aether provides pgvector semantic indexers. When users ask questions, our router calculates 1536 float arrays and retrieves matches from Supabase!";
      
      const lower = userText.toLowerCase();
      if (lower.includes("price") || lower.includes("cost") || lower.includes("billing")) {
        botResponse = "We support Stripe for global USD clients and Razorpay UPI checkout for India INR billing, dynamically routing checkouts based on user location!";
      } else if (lower.includes("n8n") || lower.includes("webhook") || lower.includes("skill")) {
        botResponse = "Yes! You can attach signed HMAC SHA256 webhook bridges straight to your agent, enabling the bot to record leads or trigger automated flows in n8n.";
      }

      setChatMessages(prev => [...prev, { role: "assistant", content: botResponse }]);
      setIsTyping(false);
    }, 1000);
  };

  const faqs: FAQItem[] = [
    {
      question: "How does Aether guarantee tenant data isolation?",
      answer: "We configure PostgreSQL Row-Level Security (RLS) policies at the database layer. Every API request attaches a verified tenant CNAME or JWT token claim, preventing cross-tenant leakage at the schema query level."
    },
    {
      question: "Does the system support high-dimensional vector lookups?",
      answer: "Yes! Aether uses PostgreSQL pgvector indexers to perform cosine similarity searches, mapping 1536-dimensional coordinate arrays deterministic floats for exact context retrieval."
    },
    {
      question: "Can I trigger n8n webhooks securely?",
      answer: "Absolutely. All webhooks generated by the Aether agent carry a signed HMAC SHA256 header encrypted with your unique workspace key, allowing n8n to verify request authenticity."
    },
    {
      question: "How does the dual-region billing gateway work?",
      answer: "Our `/api/checkout` router automatically detects geographical regions. Customers in India are routed directly to Razorpay UPI, while global customers checkout securely via Stripe Checkout."
    }
  ];

  return (
    <div className="min-h-screen bg-[#070913] text-gray-100 flex flex-col overflow-x-hidden relative font-sans selection:bg-indigo-500/30">
      
      {/* Background radial overlays */}
      <div className="absolute top-0 left-1/4 w-[600px] h-[600px] bg-indigo-500/10 rounded-full blur-[160px] pointer-events-none" />
      <div className="absolute top-1/3 right-1/4 w-[600px] h-[600px] bg-purple-500/10 rounded-full blur-[160px] pointer-events-none" />

      {/* Modern Navigation Header */}
      <header className="w-full py-6 px-8 border-b border-white/5 bg-[#070913]/70 backdrop-blur-xl fixed top-0 left-0 z-50 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="h-9 w-9 rounded-xl bg-gradient-to-tr from-indigo-500 to-purple-600 flex items-center justify-center shadow shadow-indigo-500/20">
            <Sparkles className="h-4.5 w-4.5 text-white" />
          </div>
          <span className="font-bold text-base text-white font-heading tracking-tight">Aether AI</span>
        </div>

        <nav className="hidden md:flex items-center gap-8 text-xs font-semibold text-gray-300">
          <a href="#features" className="hover:text-white transition">Features</a>
          <a href="#demo" className="hover:text-white transition">Live Agent Demo</a>
          <a href="#pricing" className="hover:text-white transition">Pricing Mesh</a>
          <a href="#faq" className="hover:text-white transition">FAQ</a>
          <Link href="/docs" className="hover:text-white transition flex items-center gap-1">
            <Code className="h-3.5 w-3.5 text-indigo-400" />
            <span>Developer Docs</span>
          </Link>
        </nav>

        <div className="flex items-center gap-4">
          <Link href="/login" className="text-xs font-bold text-gray-400 hover:text-white transition">
            Login
          </Link>
          <Link href="/onboarding" className="px-4 py-2.5 text-xs font-bold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white transition shadow shadow-indigo-600/25">
            Get Started Free
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="pt-36 pb-20 px-8 max-w-6xl w-full mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center relative">
        
        {/* Left copy */}
        <div className="lg:col-span-7 flex flex-col gap-6 text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-mono tracking-wider uppercase w-fit select-none">
            <ShieldCheck className="h-3.5 w-3.5" />
            <span>Multi-Tenant Enterprise Isolation Ready</span>
          </div>

          <h1 className="text-4xl md:text-5xl font-extrabold text-white leading-tight font-heading tracking-tight">
            Next-Gen Agentic Chatbots with <span className="bg-gradient-to-r from-indigo-400 to-purple-500 bg-clip-text text-transparent">High-Dimensional RAG</span>
          </h1>

          <p className="text-sm text-gray-400 leading-relaxed max-w-lg">
            Empower your customers with reasoning AI agents capable of querying e-commerce inventories, booking calendars, and executing cryptographically secured n8n automation webhooks.
          </p>

          <div className="flex items-center gap-4 mt-2">
            <Link href="/onboarding" className="px-6 py-3.5 text-xs font-semibold rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-2 cursor-pointer transition shadow-lg shadow-indigo-600/20 hover:scale-[1.02]">
              <span>Bootstrap Your Tenant Workspace</span>
              <ArrowRight className="h-4 w-4 text-white" />
            </Link>
            <a href="#demo" className="px-6 py-3.5 text-xs font-semibold rounded-xl border border-white/10 hover:bg-white/[0.04] text-white transition">
              Live Demo Sandbox
            </a>
          </div>
        </div>

        {/* Right Iframe/Chat Sandbox Mockup */}
        <div id="demo" className="lg:col-span-5 flex justify-center">
          <div className="w-full max-w-[340px] h-[460px] rounded-3xl premium-glass border border-white/10 p-5 flex flex-col justify-between shadow-2xl relative">
            
            {/* Header info */}
            <div className="flex items-center justify-between pb-3 border-b border-white/5 shrink-0 select-none">
              <div className="flex items-center gap-2.5">
                <div className="h-7 w-7 rounded-lg bg-indigo-600 flex items-center justify-center">
                  <Sparkles className="h-3.5 w-3.5 text-white" />
                </div>
                <div>
                  <h3 className="font-bold text-xs text-white">Aether Agent Sandbox</h3>
                  <span className="text-[8px] font-mono text-indigo-400 uppercase tracking-widest">Live playground preview</span>
                </div>
              </div>
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
            </div>

            {/* Chat Stream mockup */}
            <div className="flex-grow py-4 overflow-y-auto flex flex-col gap-3 scrollbar-none">
              {chatMessages.map((msg, i) => (
                <div 
                  key={i}
                  className={`max-w-[85%] p-3.5 rounded-2xl text-[11px] leading-relaxed ${
                    msg.role === "user"
                      ? "self-end bg-indigo-600 text-white rounded-br-none"
                      : "self-start bg-[#0a0d1a] border border-white/5 text-gray-200 rounded-bl-none shadow"
                  }`}
                >
                  <p className="whitespace-pre-wrap">{msg.content}</p>
                </div>
              ))}

              {isTyping && (
                <div className="self-start bg-[#0a0d1a] border border-white/5 p-3 rounded-2xl rounded-bl-none text-gray-500 flex items-center gap-2 text-[10px]">
                  <Loader2 className="h-3.5 w-3.5 animate-spin text-indigo-400" />
                  <span>Calculating 1536 RAG vectors...</span>
                </div>
              )}
            </div>

            {/* Input form */}
            <form onSubmit={handleDemoChat} className="pt-3 border-t border-white/5 flex gap-2 shrink-0">
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask about n8n webhooks or pricing..."
                className="flex-grow bg-[#070913] border border-white/10 rounded-xl px-3 py-2 text-[11px] focus:outline-none focus:ring-1 focus:ring-indigo-500 text-white placeholder:text-gray-600"
              />
              <button 
                type="submit" 
                disabled={isTyping || !chatInput.trim()}
                className="h-8 w-8 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white flex items-center justify-center shrink-0 disabled:opacity-40 transition"
              >
                <Send className="h-3.5 w-3.5" />
              </button>
            </form>

          </div>
        </div>

      </section>

      {/* Features Grid Section */}
      <section id="features" className="py-20 px-8 border-y border-white/5 bg-white/[0.01] relative select-none">
        <div className="max-w-5xl w-full mx-auto flex flex-col gap-12 text-center">
          
          <div className="flex flex-col gap-3">
            <span className="text-xs font-semibold text-indigo-400 uppercase tracking-widest font-mono">Platform Capabilities</span>
            <h2 className="text-2xl md:text-3xl font-extrabold text-white font-heading tracking-tight">
              State-of-the-Art Multi-Tenant Integrations
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
            
            {/* Card 1: pgvector RAG */}
            <div className="p-6 rounded-2xl bg-white/[0.01] border border-white/5 flex flex-col gap-4">
              <div className="h-10 w-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                <Database className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-sm text-white font-heading">High-Dimensional Vector RAG</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                Seamless pgvector calculations converting textual business rules to 1536 float arrays. Intercepts customer prompts and augments them instantly.
              </p>
            </div>

            {/* Card 2: Stripe + Razorpay */}
            <div className="p-6 rounded-2xl bg-white/[0.01] border border-white/5 flex flex-col gap-4">
              <div className="h-10 w-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                <Coins className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-sm text-white font-heading">Dual-Region Billing Mesh</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                Automatic geolocation routing that checks currency origins, pointing global users to Stripe Checkout and Indian users to Razorpay UPI.
              </p>
            </div>

            {/* Card 3: signed n8n webhooks */}
            <div className="p-6 rounded-2xl bg-white/[0.01] border border-white/5 flex flex-col gap-4">
              <div className="h-10 w-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                <Workflow className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-sm text-white font-heading">Secure HMAC n8n Bridges</h3>
              <p className="text-xs text-gray-400 leading-relaxed">
                Enable bot actions to trigger external workflows securely using SHA256 payload validations signed with unique tenant encryption keys.
              </p>
            </div>

          </div>

        </div>
      </section>

      {/* Phase 9: Industries Grid */}
      <section className="py-20 px-8 relative">
        <div className="max-w-6xl w-full mx-auto flex flex-col gap-12 text-center">
          <div className="flex flex-col gap-3">
            <span className="text-xs font-semibold text-indigo-400 uppercase tracking-widest font-mono">Verticals</span>
            <h2 className="text-2xl md:text-3xl font-extrabold text-white font-heading tracking-tight">
              Purpose-Built for Every Industry
            </h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { icon: Store, name: "E-Commerce", desc: "Product catalog & checkout in-chat." },
              { icon: Stethoscope, name: "Clinics & Wellness", desc: "24x7 appointment slot booking." },
              { icon: Briefcase, name: "SaaS & Agencies", desc: "Lead qualification & n8n webhooks." },
              { icon: GraduationCap, name: "Education", desc: "Course discovery & fee collection." }
            ].map((ind, i) => (
              <div key={i} className="p-6 rounded-2xl bg-[#0a0d1a]/50 border border-white/5 hover:border-indigo-500/30 hover:bg-white/[0.02] transition-all flex flex-col items-center gap-3 text-center group cursor-pointer">
                <div className="p-3 rounded-xl bg-indigo-500/10 text-indigo-400 group-hover:scale-110 transition-transform">
                  <ind.icon className="h-6 w-6" />
                </div>
                <h3 className="font-bold text-white text-sm">{ind.name}</h3>
                <p className="text-xs text-gray-500">{ind.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Phase 9: Skills Marketplace Teaser */}
      <section className="py-20 px-8 border-t border-white/5 bg-gradient-to-b from-[#0a0d1a] to-[#070913] relative">
        <div className="max-w-5xl w-full mx-auto flex flex-col md:flex-row items-center gap-12">
          <div className="flex-1 flex flex-col gap-6">
            <span className="text-xs font-semibold text-emerald-400 uppercase tracking-widest font-mono">Agentic Skills Marketplace</span>
            <h2 className="text-3xl font-extrabold text-white font-heading tracking-tight leading-tight">
              Give your agent hands. <br />Install skills in one click.
            </h2>
            <p className="text-sm text-gray-400 leading-relaxed max-w-md">
              Don't just chat. Execute. Browse our community marketplace for verified n8n webhook bridges. Install Shopify cart managers, HubSpot CRM lead syncs, or write your own custom REST API skills in seconds.
            </p>
            <Link href="/onboarding" className="w-fit px-6 py-3 text-xs font-semibold rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white transition flex items-center gap-2">
              <Workflow className="h-4 w-4" /> Browse 50+ Skills
            </Link>
          </div>
          <div className="flex-1 w-full h-[300px] relative">
             <div className="absolute inset-0 bg-gradient-to-tr from-emerald-500/10 to-indigo-500/10 rounded-3xl blur-2xl"></div>
             <div className="absolute inset-0 premium-glass border border-white/10 rounded-3xl p-6 flex flex-col gap-4 shadow-2xl">
                {/* Mock Skill Cards */}
                {[
                  { name: "Sync to HubSpot CRM", type: "n8n Webhook", verified: true },
                  { name: "Check Shopify Inventory", type: "REST API", verified: true },
                  { name: "Send Resend Email", type: "Built-in", verified: true }
                ].map((s, i) => (
                  <div key={i} className="p-3 bg-black/40 rounded-xl border border-white/5 flex items-center justify-between hover:border-emerald-500/30 transition-colors cursor-pointer">
                    <div className="flex flex-col gap-1">
                      <span className="text-sm font-bold text-white flex items-center gap-2">{s.name} <Check className="h-3 w-3 text-emerald-400" /></span>
                      <span className="text-[10px] text-gray-500 font-mono">{s.type}</span>
                    </div>
                    <button className="px-3 py-1.5 rounded-lg bg-white/5 hover:bg-emerald-500/20 hover:text-emerald-400 text-xs font-bold text-gray-300 transition">Install</button>
                  </div>
                ))}
             </div>
          </div>
        </div>
      </section>

      {/* Phase 9: Testimonials */}
      <section className="py-20 px-8 border-t border-white/5 relative">
        <div className="max-w-6xl w-full mx-auto flex flex-col gap-12 text-center">
          <h2 className="text-2xl md:text-3xl font-extrabold text-white font-heading tracking-tight">
            Trusted by 200+ Agencies & SaaS
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
            {[
              { quote: "We replaced our entire Intercom setup in 45 minutes. The n8n webhook bridge automatically qualifies our enterprise leads.", author: "Sarah Jenkins", role: "CMO, FlowState" },
              { quote: "Our restaurant bookings went up 30% because the bot takes reservations 24x7 and drops them straight into our calendar via the built-in appointment skill.", author: "Arjun Mehta", role: "Owner, Spice Grill" },
              { quote: "The dual-region checkout is magic. Our Indian customers pay via Razorpay UPI seamlessly inside the chat, while global clients get Stripe.", author: "Elena R.", role: "Founder, Zenith EdTech" }
            ].map((t, i) => (
              <div key={i} className="p-6 rounded-2xl bg-[#0a0d1a] border border-white/5 flex flex-col gap-4 relative">
                <Quote className="absolute top-6 right-6 h-6 w-6 text-white/5" />
                <div className="flex gap-1">
                  {[1,2,3,4,5].map(star => <Star key={star} className="h-4 w-4 fill-emerald-500 text-emerald-500" />)}
                </div>
                <p className="text-sm text-gray-300 leading-relaxed flex-grow">"{t.quote}"</p>
                <div className="flex items-center gap-3 pt-4 border-t border-white/5">
                  <div className="h-8 w-8 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500"></div>
                  <div className="flex flex-col">
                    <span className="text-xs font-bold text-white">{t.author}</span>
                    <span className="text-[10px] text-gray-500 font-mono">{t.role}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Grid Section */}
      <section id="pricing" className="py-20 px-8 relative">
        <div className="max-w-5xl w-full mx-auto flex flex-col gap-12">
          
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-6 border-b border-white/5 pb-6">
            <div className="flex flex-col gap-2">
              <span className="text-xs font-semibold text-indigo-400 uppercase tracking-widest font-mono">Dynamic Subscriptions</span>
              <h2 className="text-2xl md:text-3xl font-extrabold text-white font-heading tracking-tight">
                Simple, Scale-as-You-Grow Pricing
              </h2>
            </div>

            {/* Currency selector toggle */}
            <div className="flex bg-white/[0.02] border border-white/5 p-1 rounded-xl text-xs font-semibold self-start shrink-0">
              <button 
                onClick={() => setSelectedCurrency("USD")}
                className={`px-3 py-1.5 rounded-lg transition cursor-pointer ${selectedCurrency === "USD" ? "bg-indigo-600/15 text-indigo-300" : "text-gray-400 hover:text-white"}`}
              >
                Global (USD)
              </button>
              <button 
                onClick={() => setSelectedCurrency("INR")}
                className={`px-3 py-1.5 rounded-lg transition cursor-pointer ${selectedCurrency === "INR" ? "bg-indigo-600/15 text-indigo-300" : "text-gray-400 hover:text-white"}`}
              >
                India (INR)
              </button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Starter Plan */}
            <div className="p-6 rounded-2xl border border-white/5 bg-white/[0.01] hover:border-white/10 flex flex-col justify-between gap-6">
              <div className="flex flex-col gap-4">
                <div>
                  <h3 className="font-bold text-white text-base">Starter Bundle</h3>
                  <p className="text-[10px] text-gray-500 font-mono">Metered Refill ledger</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-3xl font-extrabold text-white">{selectedCurrency === "INR" ? "₹2,400" : "$29"}</span>
                  <span className="text-xs text-gray-400">/month</span>
                </div>
                <p className="text-xs text-gray-400 leading-relaxed">Perfect for scaling startups needing high reasoning density.</p>
                <div className="flex flex-col gap-2 mt-2">
                  {["50,000 AI Credits", "OpenAI & DeepSeek access", "Supabase Isolated database"].map((f, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs text-gray-300">
                      <Check className="h-4 w-4 text-indigo-400" />
                      <span>{f}</span>
                    </div>
                  ))}
                </div>
              </div>
              <Link href="/onboarding" className="w-full py-3 text-xs font-semibold rounded-xl border border-white/10 text-center text-white hover:bg-white/[0.04] transition">
                Start Free Trial
              </Link>
            </div>

            {/* Enterprise Plan */}
            <div className="p-6 rounded-2xl border border-indigo-500 bg-indigo-600/5 relative shadow-lg shadow-indigo-600/5 flex flex-col justify-between gap-6">
              <span className="absolute -top-3 right-4 bg-gradient-to-r from-indigo-500 to-purple-600 text-white text-[9px] uppercase tracking-widest font-mono font-bold px-2 py-0.5 rounded-full select-none">
                Recommended
              </span>
              <div className="flex flex-col gap-4">
                <div>
                  <h3 className="font-bold text-white text-base">Enterprise Core</h3>
                  <p className="text-[10px] text-gray-500 font-mono">High volume automation</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-3xl font-extrabold text-white">{selectedCurrency === "INR" ? "₹8,200" : "$99"}</span>
                  <span className="text-xs text-gray-400">/month</span>
                </div>
                <p className="text-xs text-gray-400 leading-relaxed">Best for high-volume customer portals and automated agents.</p>
                <div className="flex flex-col gap-2 mt-2">
                  {["500,000 AI Credits", "All 8 LLM Provider engines", "pgvector Semantic embeds", "Signed HMAC n8n bridges"].map((f, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs text-gray-300">
                      <Check className="h-4 w-4 text-indigo-400" />
                      <span>{f}</span>
                    </div>
                  ))}
                </div>
              </div>
              <Link href="/onboarding" className="w-full py-3 text-xs font-semibold rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-center text-white hover:from-indigo-500 hover:to-purple-500 transition shadow-lg shadow-indigo-600/10">
                Deploy Workspace
              </Link>
            </div>

            {/* Lite Pack */}
            <div className="p-6 rounded-2xl border border-white/5 bg-white/[0.01] hover:border-white/10 flex flex-col justify-between gap-6">
              <div className="flex flex-col gap-4">
                <div>
                  <h3 className="font-bold text-white text-base">Lite Top-Up Pack</h3>
                  <p className="text-[10px] text-gray-500 font-mono">One-off reload</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-3xl font-extrabold text-white">{selectedCurrency === "INR" ? "₹800" : "$10"}</span>
                  <span className="text-xs text-gray-400">one-off</span>
                </div>
                <p className="text-xs text-gray-400 leading-relaxed">Quick credits reload for high volume operational surges.</p>
                <div className="flex flex-col gap-2 mt-2">
                  {["10,000 AI Credits", "Instant ledger update", "Never expires"].map((f, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs text-gray-300">
                      <Check className="h-4 w-4 text-indigo-400" />
                      <span>{f}</span>
                    </div>
                  ))}
                </div>
              </div>
              <Link href="/onboarding" className="w-full py-3 text-xs font-semibold rounded-xl border border-white/10 text-center text-white hover:bg-white/[0.04] transition">
                Purchase Pack
              </Link>
            </div>

          </div>

        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-20 px-8 border-t border-white/5 bg-white/[0.01] relative">
        <div className="max-w-3xl w-full mx-auto flex flex-col gap-12">
          
          <div className="flex flex-col gap-3 text-center select-none">
            <span className="text-xs font-semibold text-indigo-400 uppercase tracking-widest font-mono">FAQ Helpcenter</span>
            <h2 className="text-2xl md:text-3xl font-extrabold text-white font-heading tracking-tight font-sans">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="flex flex-col gap-3">
            {faqs.map((faq, index) => {
              const isOpen = activeFAQ === index;
              return (
                <div 
                  key={index}
                  className="rounded-2xl border border-white/5 bg-[#0a0d1a]/50 p-4 transition-all"
                >
                  <button
                    onClick={() => handleFAQToggle(index)}
                    className="w-full flex items-center justify-between text-left font-bold text-xs md:text-sm text-white cursor-pointer select-none"
                  >
                    <span>{faq.question}</span>
                    {isOpen ? (
                      <Minus className="h-4 w-4 text-indigo-400 shrink-0" />
                    ) : (
                      <Plus className="h-4 w-4 text-indigo-400 shrink-0" />
                    )}
                  </button>

                  {isOpen && (
                    <p className="mt-3.5 text-xs text-gray-400 leading-relaxed select-text animate-fadeIn">
                      {faq.answer}
                    </p>
                  )}
                </div>
              );
            })}
          </div>

        </div>
      </section>

      {/* Minimal Footer */}
      <footer className="w-full py-8 px-8 border-t border-white/5 bg-[#070913] flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-gray-500 font-mono select-none">
        <span>© 2026 Aether AI Inc. All rights reserved.</span>
        <div className="flex items-center gap-6">
          <Link href="/docs" className="hover:text-white transition">Developer Docs</Link>
          <a href="#" className="hover:text-white transition">Privacy Policy</a>
          <a href="#" className="hover:text-white transition">Terms of Service</a>
        </div>
      </footer>

    </div>
  );
}

// Simple absolute inline loader icon mock
function Loader2({ className }: { className?: string }) {
  return (
    <svg className={`animate-spin ${className}`} fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
  );
}

// Send Icon
function Send({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24">
      <line x1="22" y1="2" x2="11" y2="13"></line>
      <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
    </svg>
  );
}
